// <auto-generated />
using CopaHAS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CopaHAS.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CopaHAS.Models.Estadio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Capacidade")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("Cidade")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("Nome")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("TB_ESTADIOS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacidade = "78838",
                            Cidade = "Rio de Janeiro",
                            Nome = "Maracaña"
                        },
                        new
                        {
                            Id = 2,
                            Capacidade = "49205",
                            Cidade = "São Paulo",
                            Nome = "Neo Química Arena"
                        },
                        new
                        {
                            Id = 3,
                            Capacidade = "61842",
                            Cidade = "Belo Horizonte",
                            Nome = "Mineirão"
                        },
                        new
                        {
                            Id = 4,
                            Capacidade = "50842",
                            Cidade = "Porto Alegre",
                            Nome = "Beira Rio"
                        },
                        new
                        {
                            Id = 5,
                            Capacidade = "50000",
                            Cidade = "Salvador",
                            Nome = "Arena Fonte Nova"
                        },
                        new
                        {
                            Id = 6,
                            Capacidade = "44000",
                            Cidade = "Manaus",
                            Nome = "Arena da Amazônia"
                        },
                        new
                        {
                            Id = 7,
                            Capacidade = "72788",
                            Cidade = "Brasília",
                            Nome = "Mané Garrincha"
                        });
                });

            modelBuilder.Entity("CopaHAS.Models.Jogador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int>("NumeroCamisa")
                        .HasColumnType("int");

                    b.Property<string>("Posicao")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int>("SelecaoId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TB_JOGADORES", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Hugo Souza",
                            NumeroCamisa = 1,
                            Posicao = "Goleiro",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Yuri Alberto",
                            NumeroCamisa = 9,
                            Posicao = "Atacante",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Danilo",
                            NumeroCamisa = 2,
                            Posicao = "Lateral Direito",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Marquinhos",
                            NumeroCamisa = 4,
                            Posicao = "Zagueiro",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Casemiro",
                            NumeroCamisa = 5,
                            Posicao = "Volante",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Alex Sandro",
                            NumeroCamisa = 6,
                            Posicao = "Lateral Esquerdo",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Lucas Paquetá",
                            NumeroCamisa = 7,
                            Posicao = "Meio Campo",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Bruno Guimarães",
                            NumeroCamisa = 8,
                            Posicao = "Meio Campo",
                            SelecaoId = 0,
                            Status = 2
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Richarlison",
                            NumeroCamisa = 10,
                            Posicao = "Atacante",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Vinicius Jr",
                            NumeroCamisa = 11,
                            Posicao = "Atacante",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 11,
                            Nome = "Rodrygo",
                            NumeroCamisa = 19,
                            Posicao = "Atacante",
                            SelecaoId = 0,
                            Status = 3
                        },
                        new
                        {
                            Id = 12,
                            Nome = "Alisson",
                            NumeroCamisa = 23,
                            Posicao = "Goleiro",
                            SelecaoId = 0,
                            Status = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
